<?php

namespace Database\Seeders;

use App\Models\Produk;
use App\Models\ProdukGambar;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProdukManualSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $produkList = [
            [
                'kode_produk' => 'PRD-231125-0101',
                'kategori_id' => 2,
                'kelompok_id' => 1,
                'nama_produk' => 'Ikan Tuna Asap',
                'brand' => 'Katapayi Holimombo Raya',
                'label_halal' => '-',
                'price' => 35000,
                'cost_price' => 30000,
                'stock' => 30,
                'description' => '-',
                'discount' => 0,
            ],
            [
                'kode_produk' => 'PRD-231125-0102',
                'kategori_id' => 2,
                'kelompok_id' => 1,
                'nama_produk' => 'Abon Ikan Tuna Sangrai (Rasa Pedas)',
                'brand' => '-',
                'label_halal' => '-',
                'price' => 15000,
                'cost_price' => 12000,
                'stock' => 65,
                'description' => '-',
                'discount' => 0,
            ],
            [
                'kode_produk' => 'PRD-231125-0103',
                'kategori_id' => 2,
                'kelompok_id' => 1,
                'nama_produk' => 'Abon Ikan Tuna Sangrai (Rasa Original)',
                'brand' => '-',
                'label_halal' => '-',
                'price' => 15000,
                'cost_price' => 12000,
                'stock' => 55,
                'description' => '-',
                'discount' => 0,
            ],
            [
                'kode_produk' => 'PRD-231125-0104',
                'kategori_id' => 2,
                'kelompok_id' => 1,
                'nama_produk' => 'Abon Ikan Tuna (Rasa Pedas)',
                'brand' => 'LIPACU',
                'label_halal' => '-',
                'price' => 15000,
                'cost_price' => 12000,
                'stock' => 65,
                'description' => '-',
                'discount' => 0,
            ],
            [
                'kode_produk' => 'PRD-231125-0105',
                'kategori_id' => 2,
                'kelompok_id' => 1,
                'nama_produk' => 'Abon Ikan Tuna (Rasa Original)',
                'brand' => 'LIPACU',
                'label_halal' => '-',
                'price' => 15000,
                'cost_price' => 12000,
                'stock' => 45,
                'description' => '-',
                'discount' => 0,
            ],
            [
                'kode_produk' => 'PRD-231125-0106',
                'kategori_id' => 2,
                'kelompok_id' => 1,
                'nama_produk' => 'Kerupuk Ikan Tuna',
                'brand' => 'LIPACU',
                'label_halal' => '-',
                'price' => 25000,
                'cost_price' => 21000,
                'stock' => 45,
                'description' => '-',
                'discount' => 0,
            ],
            [
                'kode_produk' => 'PRD-231125-0107',
                'kategori_id' => 2,
                'kelompok_id' => 2,
                'nama_produk' => 'Ikan Teri Asap',
                'brand' => '-',
                'label_halal' => '-',
                'price' => 35000,
                'cost_price' => 30000,
                'stock' => 45,
                'description' => '-',
                'discount' => 0,
            ],
            [
                'kode_produk' => 'PRD-231125-0108',
                'kategori_id' => 2,
                'kelompok_id' => 3,
                'nama_produk' => 'Kopi Bubuk',
                'brand' => 'Anes Coffee',
                'label_halal' => '-',
                'price' => 87000,
                'cost_price' => 83000,
                'stock' => 45,
                'description' => '-',
                'discount' => 0,
            ],
            [
                'kode_produk' => 'PRD-231125-0109',
                'kategori_id' => 2,
                'kelompok_id' => 4,
                'nama_produk' => 'Jahe Merah',
                'brand' => 'Oma Oma',
                'label_halal' => '-',
                'price' => 15000,
                'cost_price' => 13000,
                'stock' => 45,
                'description' => '-',
                'discount' => 0,
            ],
            [
                'kode_produk' => 'PRD-231125-0110',
                'kategori_id' => 2,
                'kelompok_id' => 4,
                'nama_produk' => 'Jahe Putih',
                'brand' => 'Oma Oma',
                'label_halal' => '-',
                'price' => 15000,
                'cost_price' => 13000,
                'stock' => 45,
                'description' => '-',
                'discount' => 0,
            ],
            [
                'kode_produk' => 'PRD-231125-0111',
                'kategori_id' => 2,
                'kelompok_id' => 5,
                'nama_produk' => 'Kacang Mete',
                'brand' => 'Assifa Mete Waole',
                'label_halal' => '-',
                'price' => 45000,
                'cost_price' => 40000,
                'stock' => 45,
                'description' => '-',
                'discount' => 0,
            ],
            [
                'kode_produk' => 'PRD-231125-0112',
                'kategori_id' => 2,
                'kelompok_id' => 6,
                'nama_produk' => 'Kemiri',
                'brand' => '-',
                'label_halal' => '-',
                'price' => 45000,
                'cost_price' => 40000,
                'stock' => 45,
                'description' => '-',
                'discount' => 0,
            ],
            [
                'kode_produk' => 'PRD-231125-0113',
                'kategori_id' => 2,
                'kelompok_id' => 7,
                'nama_produk' => 'Kacang Telur',
                'brand' => 'Aqil Aqilla',
                'label_halal' => '-',
                'price' => 64000,
                'cost_price' => 59000,
                'stock' => 45,
                'description' => '-',
                'discount' => 0,
            ],
            [
                'kode_produk' => 'PRD-231125-0114',
                'kategori_id' => 2,
                'kelompok_id' => 7,
                'nama_produk' => 'Kue Nastar',
                'brand' => 'Aqil Aqilla',
                'label_halal' => '-',
                'price' => 55000,
                'cost_price' => 50000,
                'stock' => 45,
                'description' => '-',
                'discount' => 0,
            ],
            [
                'kode_produk' => 'PRD-231125-0115',
                'kategori_id' => 2,
                'kelompok_id' => 7,
                'nama_produk' => 'Keripik Wortel',
                'brand' => 'Aqil Aqilla',
                'label_halal' => '-',
                'price' => 25000,
                'cost_price' => 23000,
                'stock' => 45,
                'description' => '-',
                'discount' => 0,
            ],
            [
                'kode_produk' => 'PRD-231125-0116',
                'kategori_id' => 2,
                'kelompok_id' => 8,
                'nama_produk' => 'Keripik Talas (Rasa Balado Pedas Manis)',
                'brand' => 'Talakea',
                'label_halal' => '-',
                'price' => 27000,
                'cost_price' => 23000,
                'stock' => 45,
                'description' => '-',
                'discount' => 0,
            ],
            [
                'kode_produk' => 'PRD-231125-0117',
                'kategori_id' => 2,
                'kelompok_id' => 8,
                'nama_produk' => 'Keripik Talas (Rasa Balado)',
                'brand' => 'Talakea',
                'label_halal' => '-',
                'price' => 27000,
                'cost_price' => 23000,
                'stock' => 45,
                'description' => '-',
                'discount' => 0,
            ],
            [
                'kode_produk' => 'PRD-231125-0118',
                'kategori_id' => 2,
                'kelompok_id' => 8,
                'nama_produk' => 'Keripik Talas (Rasa Barbeque)',
                'brand' => 'Talakea',
                'label_halal' => '-',
                'price' => 27000,
                'cost_price' => 23000,
                'stock' => 45,
                'description' => '-',
                'discount' => 0,
            ],
            [
                'kode_produk' => 'PRD-231125-0119',
                'kategori_id' => 2,
                'kelompok_id' => 8,
                'nama_produk' => 'Keripik Talas (Rasa Ekstra Pedas)',
                'brand' => 'Talakea',
                'label_halal' => '-',
                'price' => 27000,
                'cost_price' => 23000,
                'stock' => 45,
                'description' => '-',
                'discount' => 0,
            ],
            [
                'kode_produk' => 'PRD-231125-0120',
                'kategori_id' => 2,
                'kelompok_id' => 8,
                'nama_produk' => 'Keripik Talas (Rasa Jagung Bakar)',
                'brand' => 'Talakea',
                'label_halal' => '-',
                'price' => 27000,
                'cost_price' => 23000,
                'stock' => 45,
                'description' => '-',
                'discount' => 0,
            ],
            [
                'kode_produk' => 'PRD-231125-0121',
                'kategori_id' => 2,
                'kelompok_id' => 8,
                'nama_produk' => 'Keripik Talas (Rasa Karamel)',
                'brand' => 'Talakea',
                'label_halal' => '-',
                'price' => 27000,
                'cost_price' => 23000,
                'stock' => 45,
                'description' => '-',
                'discount' => 0,
            ],
            [
                'kode_produk' => 'PRD-231125-0122',
                'kategori_id' => 2,
                'kelompok_id' => 8,
                'nama_produk' => 'Keripik Talas (Rasa Original)',
                'brand' => 'Talakea',
                'label_halal' => '-',
                'price' => 27000,
                'cost_price' => 23000,
                'stock' => 45,
                'description' => '-',
                'discount' => 0,
            ],
            [
                'kode_produk' => 'PRD-231125-0123',
                'kategori_id' => 2,
                'kelompok_id' => 9,
                'nama_produk' => 'Keripik Keju',
                'brand' => 'Mawaddah',
                'label_halal' => '-',
                'price' => 25000,
                'cost_price' => 21000,
                'stock' => 45,
                'description' => '-',
                'discount' => 0,
            ],
            [
                'kode_produk' => 'PRD-231125-0124',
                'kategori_id' => 2,
                'kelompok_id' => 9,
                'nama_produk' => 'Kue Sagu',
                'brand' => 'Mawaddah',
                'label_halal' => '-',
                'price' => 28000,
                'cost_price' => 21000,
                'stock' => 45,
                'description' => '-',
                'discount' => 0,
            ],
            [
                'kode_produk' => 'PRD-231125-0125',
                'kategori_id' => 2,
                'kelompok_id' => 9,
                'nama_produk' => 'Kacang Telur',
                'brand' => 'Mawaddah',
                'label_halal' => '-',
                'price' => 25000,
                'cost_price' => 22000,
                'stock' => 45,
                'description' => '-',
                'discount' => 0,
            ],
            [
                'kode_produk' => 'PRD-231125-0126',
                'kategori_id' => 1,
                'kelompok_id' => 10,
                'nama_produk' => 'Kain Tenun Pewarna Alam',
                'brand' => 'Wagaga',
                'label_halal' => '-',
                'price' => 150000,
                'cost_price' => 147000,
                'stock' => 45,
                'description' => '-',
                'discount' => 0,
            ],
            [
                'kode_produk' => 'PRD-231125-0127',
                'kategori_id' => 1,
                'kelompok_id' => 10,
                'nama_produk' => 'Kain Tenun Pewarna Sintetis',
                'brand' => 'Wagaga',
                'label_halal' => '-',
                'price' => 150000,
                'cost_price' => 147000,
                'stock' => 45,
                'description' => '-',
                'discount' => 0,
            ],
        ];

        foreach ($produkList as $p) {
            Produk::updateOrCreate(
                ['kode_produk' => $p['kode_produk']],
                $p
            );
        }

        // PRODUK GAMBAR
        // for ($i = 1; $i <= 27; $i++) {
        //     ProdukGambar::updateOrCreate(
        //         ['kode_produk' => 'PRD-231125-' . str_pad($i + 100, 4, '0', STR_PAD_LEFT)],
        //         ['gambar' => "produk-images/{$i}.jpg"]
        //     );
        // }
    }
}
